; Nagara pickup sensor is supported through hybris "wakeup sensor"
; Just have to adjust sensor_type and enable it
; SENSOR_TYPE_PICK_UP_GESTURE = 25

[wakeup]
sensor_type=25

[plugins]
wakeupadaptor = hybriswakeupadaptor

[available]
wakeupsensor=True
